# Generated by Django 4.1.7 on 2023-04-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0004_profile_source_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='User',
            new_name='user',
        ),
    ]
