# Generated by Django 4.1.7 on 2023-04-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0005_rename_user_income_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='source',
        ),
        migrations.AddField(
            model_name='profile',
            name='spend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
