# Generated by Django 4.1.7 on 2023-04-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0007_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=200)),
                ('goal_number', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_income', models.CharField(choices=[('vacation', 'Vacation / travel'), ('emergency', 'Emergency fund'), ('debt', 'Debt repayment'), ('invest', 'Investing'), ('homeownership', 'Homeownership'), ('other', 'Other goals')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
