# Generated by Django 4.1.7 on 2023-05-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0008_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
